repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # Change this to the latest version
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black