from setuptools import setup

setup(
    name="BINocular",
    version="1.1",
    description="Common Binary Framework",
    author="Brandon Wong",
    packages=["binocular"],
    install_requires=[
        "rich",
        "click<8.2.0",
        "typer==0.15.2",
        "pydantic",
        "networkx",
        "coloredlogs",
        "archinfo",
        "pyvex",
        "GitPython",
        "meson",
        "rzpipe",
        "tree-sitter==0.23.1",
        "tree-sitter-c==0.23.1",
        "requests",
        "IPython",
        "sphinx",
        "pyghidra",
    ],
    extras_require={
        "dev": [
            "pre-commit",
            "mypy",
            "pytest",
            "sphinx",
            "sphinx_rtd_theme",
            "sphinx_mdinclude",
            "build",
            "types-networkx",
            "black",
            "types-requests",
            "ghidra-stubs==12.0.0",
        ]
    },
    entry_points={"console_scripts": ["binocular = binocular.run:main"]},
    package_data={"binocular": ["scripts/*"]},
)
